# Generated by Django 5.2.7 on 2026-04-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table=None,
        ),
    ]
