# Generated by Django 5.2.7 on 2026-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_bus_description_alter_bus_status_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='RouteStop',
        ),
    ]
